# Generated by Django 4.1.2 on 2024-04-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_archiveditem_pointgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointgroup',
            name='eight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_eight+', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='nine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_nine+', to='archive.archiveditem'),
        ),
    ]
