# Generated by Django 4.1.2 on 2024-04-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_pointgroup_eight_alter_pointgroup_nine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointgroup',
            name='eight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_eight', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='five',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_five', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='four',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_four', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='nine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_nine', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_one', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='seven',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_seven', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='six',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_six', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='three',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_three', to='archive.archiveditem'),
        ),
        migrations.AlterField(
            model_name='pointgroup',
            name='two',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_two', to='archive.archiveditem'),
        ),
    ]
