# Generated by Django 4.1.2 on 2024-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_pointgroup_eight_alter_pointgroup_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveditem',
            name='gridID',
        ),
        migrations.RemoveField(
            model_name='archiveditem',
            name='pixel',
        ),
        migrations.AlterField(
            model_name='archiveditem',
            name='name',
            field=models.EmailField(max_length=50),
        ),
    ]
