# Generated by Django 4.1.2 on 2024-04-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_remove_archiveditem_gridid_remove_archiveditem_pixel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tx_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
