# Generated by Django 4.1.2 on 2024-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_archiveditem_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveditem',
            name='url',
            field=models.URLField(),
        ),
    ]
